CREATE TABLE employees (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'active',
    document_path VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nik VARCHAR(255) UNIQUE,
    gender enum_employees_gender,
    birth_place VARCHAR(255),
    birth_date DATE,
    username VARCHAR(255) UNIQUE,
    contract_start_date DATE,
    contract_end_date DATE,
    marital_status VARCHAR(255),
    bpjs_doctor_code VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    address TEXT,
    role VARCHAR(255)
);